Changes....

diff --git a/dti_preproc b/dti_preproc
--- a/dti_preproc
+++ b/dti_preproc
@@ -219,7 +219,7 @@ end
 if ( ! -e ${aout}_dti_to_free.mat || $?force == 1 ) then
 	set cmd = ( $FREESURFER_HOME/bin/bbregister --mov ${dout}_b0.nii.gz )
 	set cmd = ( $cmd --s $subj --reg ${aout}_dti_to_free.dat --init-fsl --dti )
-	set cmd = ( $cmd --o ${aout}_dti_to_free.nii.gz --fslmat ${aout}_dti_to_free.mat )
+	set cmd = ( $cmd --o ${aout}_dti_to_free_lin.nii.gz --fslmat ${aout}_dti_to_free.mat )
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 endif
 
@@ -238,7 +238,7 @@ if ( ! -e ${aout}_dti_to_free_std.mat || $?force == 1 ) then
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 endif
 
-#Use FSL to invert dist_dti to T1 transform
+#Use FSL to invert dti to T1 transform
 if ( ! -e ${aout}_free_to_dti.mat || $?force == 1 ) then
 	set cmd = ( $FSLDIR/bin/convert_xfm -inverse ${aout}_dti_to_free.mat )
 	set cmd = ( $cmd -omat ${aout}_free_to_dti.mat )
@@ -260,10 +260,10 @@ endif
 
 #Use FSL to nonlinear registration between dti and T1
 if ( ! -e ${aout}_dti_to_free_coef.nii.gz || $?force == 1 ) then
-	#set cmd = ( $FSLDIR/bin/fnirt --in=${dout}_FA_ero --ref=${aout}_T1_std )
-	#set cmd = ( $cmd --aff=${aout}_dti_to_free_std.mat --cout=${aout}_dti_to_free_coef )
-	#set cmd = ( $cmd --iout=${aout}_dti_to_free_warp )
-	#echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	set cmd = ( $FSLDIR/bin/fnirt --in=${dout}_FA_ero --ref=${aout}_T1_std )
+	set cmd = ( $cmd --aff=${aout}_dti_to_free_std.mat --cout=${aout}_dti_to_free_coef )
+	set cmd = ( $cmd --iout=${aout}_dti_to_free_nonlin )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 endif
 	
 #Use FSL to do a linear registertion between T1 and MNI152
@@ -296,7 +296,7 @@ endif
 
 set qdir = $outdir/qa
 if ( ! -d $qdir ) mkdir $qdir
-set qout = $qdir/$root
+set qout = $qdir/${root}_dti
 
 #Use FSL to make motion plots (slightly modified from the following mailing list post by Mark Jenkinson
 #https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1101&L=FSL&D=0&1=FSL&9=A&J=on&d=No+Match%3BMatch%3BMatches&z=4&P=118462
@@ -354,6 +354,124 @@ if ( ! -e ${qout}_dti_disp.png || ! -e ${qout}_dti_rot.png || ! -e ${qout}_dti_t
 	set cmd = ( $cmd qa_curr.mat ); echo $cmd |& tee -a $log; $cmd |& tee -a $log
 endif
 
+
+#Setup slicer and png_append options
+set sliceropts = ( -s 2 -x 0.5 sla.png -x 0.45 slb.png -x 0.55 slc.png -x 0.65 sld.png -y 0.35 \
+					sle.png -y 0.45 slf.png -y 0.55 slg.png -y 0.65 slh.png -z 0.35 sli.png \
+					-z 0.45 slj.png -z 0.55 slk.png -z 0.65 sll.png )
+set appendopts = ( sla.png + slb.png + slc.png + sld.png + sle.png + slf.png + slg.png + slh.png \
+					+ sli.png + slj.png + slk.png + sll.png )
+
+#Use FSL to get brain mask QA image
+if ( ! -e ${qout}_brain_mask_qa.png || $?force == 1 ) then
+	#Get non-eroded qa image
+	set cmd = ( $FSLDIR/bin/slicer ${dout}_b0_brain ${dout}_b0_brain_mask $sliceropts )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_brain_mask_qa.png )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+	#Cleanup
+	echo rm sl?.png |& tee -a $log; rm sl?.png |& tee -a $log
+endif
+
+#Use FSL to get tensor fit SSE
+if ( ! -e ${qout}_sse_qa.png ) then
+	#Get before residual qa image
+	set cmd = ( $FSLDIR/bin/slicer ${dout}_sse $sliceropts )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_sse_qa.png )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+	#Cleanup
+	echo rm sl?.png |& tee -a $log; rm sl?.png |& tee -a $log
+endif
+
+#Use FSL to get DTI->T1 registration qa images
+foreach reg ( lin nonlin )
+	if ( ! -e ${qout}_dti_to_free_${reg}_qa.png || $?force == 1 ) then
+		
+		#Get diffusion outlines
+		set cmd = ( $FSLDIR/bin/slicer ${aout}_T1_std ${aout}_dti_to_free_${reg} $sliceropts )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+		set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_dti_to_free_${reg}_qa1.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+		
+		#Get T1 outlines
+		set cmd = ( $FSLDIR/bin/slicer ${aout}_dti_to_free_${reg} ${aout}_T1_std $sliceropts )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+		set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_dti_to_free_${reg}_qa2.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+		#Combine QA Images
+		set cmd = ( $FSLDIR/bin/pngappend ${qout}_dti_to_free_${reg}_qa1.png )
+		set cmd = ( $cmd - ${qout}_dti_to_free_${reg}_qa2.png ${qout}_dti_to_free_${reg}_qa.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log	
+	
+		#Cleanup
+		echo rm sl?.png |& tee -a $log; rm sl?.png |& tee -a $log
+	endif
+end
+
+#Use FSL to get free to MNI 152 space QA
+foreach reg ( lin nonlin )
+	if ( ! -e ${qout}_free_to_MNI152_${reg}_qa.png || $?force == 1 ) then
+		#Use FSL to get free to MNI152 QA (MNI Outlines)
+		set cmd = ( $FSLDIR/bin/slicer ${aout}_free_to_MNI152_${reg} )
+		set cmd = ( $cmd ${FSLDIR}/data/standard/MNI152_T1_2mm_brain $sliceropts )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+		set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_free_to_MNI152_${reg}_qa1.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+		#Use FSL to get free to MNI 152 QA (free standard outlines)
+		set cmd = ( $FSLDIR/bin/slicer ${FSLDIR}/data/standard/MNI152_T1_2mm_brain )
+		set cmd = ( $cmd ${aout}_free_to_MNI152_${reg} $sliceropts )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+		set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_free_to_MNI152_${reg}_qa2.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+		#Combine QA Images
+		set cmd = ( $FSLDIR/bin/pngappend ${qout}_free_to_MNI152_${reg}_qa1.png )
+		set cmd = ( $cmd - ${qout}_free_to_MNI152_${reg}_qa2.png ${qout}_free_to_MNI152_${reg}_qa.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log	
+	
+		#Cleanup
+		echo rm sl?.png |& tee -a $log; rm sl?.png |& tee -a $log
+	endif
+end
+
+#Use FSL to get free to MNI 152 space QA
+foreach dtireg ( lin nonlin )
+	foreach freereg ( lin nonlin )
+	if ( ! -e ${qout}_free_to_MNI152_${reg}_qa.png || $?force == 1 ) then
+		#Use FSL to get free to MNI152 QA (MNI Outlines)
+		set cmd = ( $FSLDIR/bin/slicer ${aout}_free_to_MNI152_${reg} )
+		set cmd = ( $cmd ${FSLDIR}/data/standard/MNI152_T1_2mm_brain $sliceropts )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+		set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_free_to_MNI152_${reg}_qa1.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+		#Use FSL to get free to MNI 152 QA (free standard outlines)
+		set cmd = ( $FSLDIR/bin/slicer ${FSLDIR}/data/standard/MNI152_T1_2mm_brain )
+		set cmd = ( $cmd ${aout}_free_to_MNI152_${reg} $sliceropts )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+		set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_free_to_MNI152_${reg}_qa2.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+		#Combine QA Images
+		set cmd = ( $FSLDIR/bin/pngappend ${qout}_free_to_MNI152_${reg}_qa1.png )
+		set cmd = ( $cmd - ${qout}_free_to_MNI152_${reg}_qa2.png ${qout}_free_to_MNI152_${reg}_qa.png )
+		echo $cmd |& tee -a $log; $cmd |& tee -a $log	
+	
+		#Cleanup
+		echo rm sl?.png |& tee -a $log; rm sl?.png |& tee -a $log
+	endif
+end
+
+
+################
+###QA Webpage###
+################
+
 #Put Everything in a QA webpage
 if ( ! -e ${qout}_${program}_qa_index.html || $?force == 0 ) then
 	echo "Creating QA webpage at: `pwd`/${qout}_${program}_qa_index.html" |& tee -a $log
@@ -385,7 +503,7 @@ if ( ! -e ${qout}_${program}_qa_index.html || $?force == 0 ) then
 		  Row 2: Mask used for normalization and regression (Eroded version of Row 1). \
 		 <p><IMG BORDER=0 SRC=${root}_brain_mask_qa.png>" >> ${qout}_${program}_qa_bmsk.html
 		 
-	#Setup Standard Deviation Image
+	#Setup SSE
 	echo "<hr><h2>Standard Deviation Images</h2>" >> ${qout}_${program}_qa_stdev.html
 	echo "Row 1: Before Residual Temporal Standard Deviation. \
 		  Row 2: After Residual Temporal Standard Deviation. \
