fc_preproc changes....

diff --git a/fc_preproc b/fc_preproc
--- a/fc_preproc
+++ b/fc_preproc
@@ -25,6 +25,7 @@ if ( $#argv == 0 ) then
 	echo "	-mag: <mag>		Nifti field map magnitude image."
 	echo "	-phase: <phase>		Nifti field map phase image."
 	echo "	-te: <te>		Bold echo time."
+	echo "	-trep: <trep>	Bold repetition time." 
 	echo "	-dwell: <dwell>		Diffusion dwell time."
 	echo "	-delta: <delta>		Difference between field map echo times."
 	echo ""
@@ -110,17 +111,11 @@ end
 if ( $?debug == 1 ) set echo
 
 #Check to make sure all required options have been set
-if ( $?bold == 0 || $?subj == 0 || $?trep == 0 ) then
-	echo "Missing required arguments. See usage."
-	exit 1
-endif
-
-#Check to make sure all required options have been set
 if ( $?nodist == 1 && ( $?bold == 0 || $?subj == 0 || $?trep == 0 ) ) then
 	echo "Missing required arguments. See usage."
 	exit 1
-else if ( $?bold == 0 || $?subj == 0 || $?trep == 0 || $?mag == 0 || $?phase == 0 || $?te == 0 \
-		|| $?dwell == 0 || $?delta == 0 ) then
+else if ( $?nodist == 0 && ( $?bold == 0 || $?subj == 0 || $?trep == 0 || $?mag == 0 || \
+			$?phase == 0 || $?te == 0 || $?dwell == 0 || $?delta == 0 ) ) then
 	echo "Missing required arguments. See usage."
 	exit 1
 endif
@@ -195,12 +190,11 @@ if ( ! -e ${bpre}_eq.nii.gz || $?force == 1 ) then
 endif
 set bpre = "${bpre}_eq"
 
-#Use FSL to get bold standard deviation image
 if ( ! -e ${bpre}_stdev.nii.gz || $?force == 1 ) then
-		set cmd = ( $FSLDIR/bin/fslmaths ${bpre} -Tstd ${bpre}_stdev )
-		echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	set cmd = ( $FSLDIR/bin/fslmaths ${bpre} -Tstd ${bpre}_stdev )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 endif
-
+	
 #If user wants, use FSL to due slicetime correction
 if ( $?stcf == 1 && ( ! -e ${bpre}_stc.nii.gz || $?force == 1 ) ) then
 	set cmd = ( $FSLDIR/bin/slicetimer -i ${bpre} -o ${bpre}_stc --ocustom=$stcf -r $trep )
@@ -219,11 +213,23 @@ if ( $?nodist == 0 ) then
 	#Run distortion/motion correction
 	if ( ! -e ${uout}_epi_undist_mcf.nii.gz || $?force == 1 ) then
 		set cmd = ( epi_unwarp -m $mag -p $phase -e ${bpre} -dwell $dwell -te $te -delta $delta )
-		set cmd = ( $cmd -epibet $bthresh -boldmc -o $udir -r ${root} -debug -ref $refvol )
+		set cmd = ( $cmd -epibet $bthresh -boldmc -o $udir -r ${root} -debug -frame $refvol )
 		echo $cmd |& tee -a $log; $cmd |& tee -a $log
 	endif
 	set bpre = "${bpre}_undist_mcf"
 	set mcf = "${bpre}"
+	
+	#Copy over motion correction outputs
+	foreach mfile ( .mat _abs.rms _abs_mean.rms .par _rel.rms _rel_mean.rms )
+		if ( ! -e ${mcf}${mfile} || $?force == 1 ) then
+			if ( $mfile == .mat ) then
+				set cmd = ( cp -r ${uout}_mcf${mfile} ${mcf}${mfile} )
+			else 
+				set cmd = ( cp ${uout}_mcf${mfile} ${mcf}${mfile} )
+			endif
+			echo $cmd |& tee -a $log; $cmd |& tee -a $log
+		endif
+	end
 	
 	#Copy over undistorted reference
 	if ( ! -e ${bpre}_ref.nii.gz || $?force == 1 ) then
@@ -233,7 +239,7 @@ if ( $?nodist == 0 ) then
 	
 	#Copy over brain mask (generated from magnitude image)
 	if ( ! -e ${bpre}_ref_brain_mask.nii.gz || $?force == 1 ) then
-		set cmd = ( $FSLDIR/bin/imcp ${uout}_mag_brain_mask_to_${root}_epi_0_brain )
+		set cmd = ( $FSLDIR/bin/imcp ${uout}_mag_brain_mask_to_${root}_epi_${refvol}_brain )
 		set cmd = ( $cmd ${bpre}_ref_brain_mask )
 		echo $cmd |& tee -a $log; $cmd |& tee -a $log
 	endif
@@ -248,7 +254,7 @@ if ( $?nodist == 0 ) then
 	
 	#Copy over the whole undistorted series
 	if ( ! -e ${bpre}_brain.nii.gz || $?force == 1 ) then
-		set cmd = ( $FSLDIR/bin/imcp ${uout}_epi_undist_mcf ${dout}_eddy )
+		set cmd = ( $FSLDIR/bin/imcp ${uout}_epi_undist_mcf ${bpre}_brain )
 		echo $cmd |& tee -a $log; $cmd |& tee -a $log
 	endif
 	set bpre = "${bpre}_brain"
@@ -294,16 +300,9 @@ if ( ! -e ${bpre}_${fwhm}fwhm.nii.gz || $?force == 1 ) then
 endif
 set bpre = "${bpre}_${fwhm}fwhm"
 
-#Use Freesurfer to erode mask for use in normalization and regressing 
-if ( ! -e ${bout}_wb_bold_mask.nii.gz || $?force == 1 ) then
-	set cmd = ( $FREESURFER_HOME/bin/mri_binarize --i $mask  --erode 1 --min 1 )
-	set cmd = ( $cmd --zero-edges --o ${bout}_wb_bold_mask.nii.gz )
-	echo $cmd |& tee -a $log; $cmd |& tee -a $log
-endif
-
 #Use FSL to do grand mean normalization
 if ( ! -e ${bpre}_norm.nii.gz || $?force == 1 ) then
-	set int_fifty = `$FSLDIR/bin/fslstats ${bpre} -k ${bout}_wb_bold_mask -p 50`
+	set int_fifty = `$FSLDIR/bin/fslstats ${bpre} -k $bold_mask -p 50`
 	set scale = `echo "scale=5; 10000 / $int_fifty" | bc -l`
 	set cmd = ( $FSLDIR/bin/fslmaths ${bpre} -mul $scale ${bpre}_norm )
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
@@ -395,7 +394,7 @@ if ( ! -e ${aout}_free_warped_to_MNI152.nii.gz || $?force == 1 ) then
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 endif
 
-#Use FSL to apply nonlinear registration to DTI data
+#Use FSL to apply nonlinear registration to BOLD data
 if ( ! -e ${aout}_bold_warped_to_MNI152.nii.gz || $?force == 1 ) then
 	set cmd = ( $FSLDIR/bin/applywarp --in=$bold_ref --out=${aout}_bold_warped_to_MNI152 )
 	set cmd = ( $cmd --ref=${FSLDIR}/data/standard/MNI152_T1_2mm_brain )
@@ -433,7 +432,7 @@ endif
 foreach tissue ( "ventricles" "wm" "wb" )	
 	if ( $tissue == "wb" ) then
 		if ( ( ! -e ${rout}_wb_bold_mask.nii.gz || $?force == 1 ) && $?wbreg == 1 ) then
-			set cmd = ( cp ${bout}_wb_bold_mask.nii.gz $outdir/regress/ )
+			set cmd = ( cp $bold_mask.nii.gz $outdir/regress/ )
 			echo $cmd |& tee -a $log; $cmd |& tee -a $log
 		else
 			continue
@@ -448,7 +447,7 @@ foreach tissue ( "ventricles" "wm" "wb" )
 		#Use FSL to transform masks to bold space
 		if ( ! -e ${rout}_${tissue}_bold.nii.gz || $?force == 1 ) then
 			set cmd = ( $FSLDIR/bin/applywarp -i ${rout}_${tissue} --premat=${aout}_free_to_bold.mat )
-			set cmd = ( $cmd -r ${bout}_bold_eq_ref -o ${rout}_${tissue}_bold )
+			set cmd = ( $cmd -r ${bold_ref} -o ${rout}_${tissue}_bold )
 			echo $cmd |& tee -a $log; $cmd |& tee -a $log
 		endif
 		#Use FSL to rebinarize masks in bold space
@@ -540,20 +539,9 @@ set appendopts = ( sla.png + slb.png + slc.png + sld.png + sle.png + slf.png + s
 #Use FSL to get brain mask QA image
 if ( ! -e ${qout}_bold_brain_mask_qa.png || $?force == 1 ) then
 	#Get non-eroded qa image
-	set cmd = ( $FSLDIR/bin/slicer ${bout}_bold_eq_ref $bold_mask $sliceropts )
+	set cmd = ( $FSLDIR/bin/slicer ${bold_ref} $bold_mask $sliceropts )
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
-	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_bold_brain_mask_nonero_qa.png )
-	echo $cmd |& tee -a $log; $cmd |& tee -a $log
-	
-	#Get eroded brainmask image
-	set cmd = ( $FSLDIR/bin/slicer ${bout}_bold_eq_ref ${bout}_wb_bold_mask $sliceropts )
-	echo $cmd |& tee -a $log; $cmd |& tee -a $log
-	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_bold_wb_bold_mask_qa.png )
-	echo $cmd |& tee -a $log; $cmd |& tee -a $log
-	
-	#Combine QA images
-	set cmd = ( $FSLDIR/bin/pngappend ${qout}_bold_brain_mask_nonero_qa.png )
-	set cmd = ( $cmd - ${qout}_bold_wb_bold_mask_qa.png ${qout}_bold_brain_mask_qa.png )
+	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_bold_brain_mask_qa.png )
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 	
 	#Cleanup
@@ -583,10 +571,33 @@ if ( ! -e ${qout}_bold_stdev_qa.png ) then
 	echo rm sl?.png |& tee -a $log; rm sl?.png |& tee -a $log
 endif
 
+#Use FSL to get distortion correction QA
+if ( $?nodist == 0 && ( ! -e ${qout}_bold_distcorrect.png || $?force == 1 ) ) then
+	#Get distorted images
+	set cmd = ( $FSLDIR/bin/slicer ${uout}_epi_${refvol}_brain $sliceropts )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_bold_distorted.png )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+	#Get undistorted images
+	set cmd = ( $FSLDIR/bin/slicer $bold_ref $sliceropts )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_bold_undistorted.png )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+	#Combine Images
+	set cmd = ( $FSLDIR/bin/pngappend ${qout}_bold_distorted.png - ${qout}_bold_undistorted.png )
+	set cmd = ( $cmd ${qout}_bold_distcorrect.png )
+	echo $cmd |& tee -a $log; $cmd |& tee -a $log
+	
+	#Cleanup
+	echo rm sl?.png |& tee -a $log; rm sl?.png |& tee -a $log
+endif
+
 #Use FSL to get bold/free registration QA
 if ( ! -e ${qout}_bold_to_free_std_qa.png || $?force == 1 ) then
 	#Use FSL transform bold ref to T1 with standard orientation
-	set cmd = ( $FSLDIR/bin/flirt -in ${bout}_bold_eq_ref -ref ${aout}_T1_std -applyxfm -init )
+	set cmd = ( $FSLDIR/bin/flirt -in ${bold_ref} -ref ${aout}_T1_std -applyxfm -init )
 	set cmd = ( $cmd ${aout}_bold_to_free_std.mat -o ${qout}_bold_to_free_std )
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 	
@@ -614,7 +625,7 @@ endif
 #Use FSL to get free to MNI 152 space QA
 if ( ! -e ${qout}_free_to_MNI152_qa.png || $?force == 1 ) then
 	#Use FSL to get free to MNI152 QA (MNI Outlines)
-	set cmd = ( $FSLDIR/bin/slicer ${aout}_free_to_MNI152_nolin )
+	set cmd = ( $FSLDIR/bin/slicer ${aout}_free_warped_to_MNI152 )
 	set cmd = ( $cmd ${FSLDIR}/data/standard/MNI152_T1_2mm_brain $sliceropts )
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_free_to_MNI152_qa1.png )
@@ -639,7 +650,7 @@ endif
 #Use FSL to get bold to MNI 152 space QA
 if ( ! -e ${qout}_bold_to_MNI152_qa.png || $?force == 1 ) then
 	#Use FSL to get free to MNI152 QA (MNI Outlines)
-	set cmd = ( $FSLDIR/bin/slicer ${qout}_bold_warped_to_MNI152)
+	set cmd = ( $FSLDIR/bin/slicer ${aout}_bold_warped_to_MNI152)
 	set cmd = ( $cmd ${FSLDIR}/data/standard/MNI152_T1_2mm_brain $sliceropts )
 	echo $cmd |& tee -a $log; $cmd |& tee -a $log
 	set cmd = ( $FSLDIR/bin/pngappend $appendopts ${qout}_bold_to_MNI152_qa1.png )
@@ -673,10 +684,10 @@ if ( ! -e ${qout}_bold_qa_index.html || $?force == 1 ) then
 	#Setup header
 	echo '<html><body bgcolor="gray">' | tee $web_list > /dev/null
 	echo "<center><h1>${program}: ${subj} Quick QA</center></h1>" | tee -a $web_list > /dev/null
-	echo "<center><a href=${root}_${program}_qa_mc.html>Motion_Correction</a href> - \
-		  <a href=${root}_${program}_qa_bmsk.html>Brain Masking</a href> - \
-		  <a href =${root}_${program}_qa_stdev.html>Standard Deviation</a href> -\
-		  <a href=${root}_${program}_qa_reg.html>Registration</a ref></center> " | tee -a $web_list > /dev/null
+	echo "<center><a href=${root}_bold_qa_mc.html>Motion_Correction</a href> - \
+		  <a href=${root}_bold_qa_bmsk.html>Brain Masking</a href> - \
+		  <a href =${root}_bold_qa_stdev.html>Standard Deviation</a href> -\
+		  <a href=${root}_bold_qa_reg.html>Registration</a ref></center> " | tee -a $web_list > /dev/null
 	
 	#Setup Motion Correction
 	echo "<hr><h2>Motion Correction</h2>" >> ${qout}_bold_qa_mc.html
@@ -691,9 +702,12 @@ if ( ! -e ${qout}_bold_qa_index.html || $?force == 1 ) then
 	
 	#Setup Brain Masking
 	echo "<hr><h2>Brain Masking</h2>" >> ${qout}_bold_qa_bmsk.html
-	echo "Row 1: Mask used for registration (Run using FSL's bet and -f _3 and -R options). \
-		  Row 2: Mask used for normalization and regression (Eroded version of Row 1). \
-		 <p><IMG BORDER=0 SRC=${root}_bold_brain_mask_qa.png>" >> ${qout}_bold_qa_bmsk.html
+	if ( $?nodist == 0 ) then
+		echo "Mask was generated from field map magnitude image and transformed to BOLD space." >> ${qout}_bold_qa_bmsk.html
+	else
+		echo "Mask was generated using BET with the -R and -f $bthresh options" >>${qout}_bold_qa_bmsk.html
+	endif
+	echo "<p><IMG BORDER=0 SRC=${root}_bold_brain_mask_qa.png>" >> ${qout}_bold_qa_bmsk.html
 		 
 	#Setup Standard Deviation Image
 	echo "<hr><h2>Standard Deviation Images</h2>" >> ${qout}_bold_qa_stdev.html
@@ -703,6 +717,10 @@ if ( ! -e ${qout}_bold_qa_index.html || $?force == 1 ) then
 		 
 	#Setup Registration
 	echo "<hr><h2>Registration</h2>" >>  ${qout}_bold_qa_reg.html
+	if ( $?nodist == 0 ) then
+		echo "BOLD Distortion Correction (Distorted=Top, Undistorted=Bottom)" >> ${qout}_bold_qa_reg.html
+		echo "<p><IMG BORDER=0 SRC=${root}_bold_distcorrect.png WIDTH=2000><p>" >> ${qout}_bold_qa_reg.html
+	endif
 	set bbcost = `awk '{print $1}' ${aout}_bold_to_free.dat.mincost`
 	echo "BOLD to FreeSurfer T1 - bbregister final cost: $bbcost " >> ${qout}_bold_qa_reg.html
 	echo "<p><IMG BORDER=0 SRC=${root}_bold_to_free_std_qa.png WIDTH=2000>" >> ${qout}_bold_qa_reg.html
